fields:
  block_content:
    langcode:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    info:
      type: hidden
      settings: {  }
    changed:
      type: hidden
      settings: {  }
    revision_created:
      type: hidden
      settings: {  }
    revision_user:
      type: hidden
      settings: {  }
    default_langcode:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    body:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
  node:
    langcode:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    revision_timestamp:
      type: hidden
      settings: {  }
    status:
      type: hidden
      settings: {  }
    title:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    uid:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    created:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    changed:
      type: hidden
      settings: {  }
    promote:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    sticky:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    default_langcode:
      type: hidden
      settings: {  }
    revision_translation_affected:
      type: hidden
      settings: {  }
    body:
      type: text_field_diff_builder
      settings:
        compare_format: 0
        show_header: 1
        markdown: drupal_html_to_text
    comment:
      type: comment_field_diff_builder
      settings:
        compare_key: 0
        compare_string: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_featured_image:
      type: image_field_diff_builder
      settings:
        show_id: 0
        compare_alt_field: 1
        compare_title_field: 1
        property_separator: nl
        show_thumbnail: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_image:
      type: image_field_diff_builder
      settings:
        show_id: 0
        compare_alt_field: 1
        compare_title_field: 1
        property_separator: nl
        show_thumbnail: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_press_release_number:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_publication_date:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_subtitle:
      type: core_field_diff_builder
      settings:
        show_header: 1
        markdown: drupal_html_to_text
    field_tags:
      type: entity_reference_field_diff_builder
      settings:
        compare_entity_reference: 1
        show_header: 1
        markdown: drupal_html_to_text
    field_workflow_state:
      type: hidden
      settings: {  }
