_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: a8610938-ba2d-4f34-a473-bac1d92b4311
name: Weather.gov
mail: admin@noaa.gov
slogan: 'National Weather Service'
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
